#!/bin/bash

PASSWORD="/root/.ethereum/password"

swarm version

#IP="localhost"
IPC=/root/.ethereum/devchain/geth.ipc
#BZZKEY=`geth account list | sed "s/.*{\(.*\)}.*/\1/1"` && \
swarm --bzzaccount "007ccffb7916f37f7aeef05e8096ecfbe55afc2f" --password "" --bzzport 8500 --ens-api $IPC
  #swarm --bzzaccount $BZZKEY --password $PASSWORD --bzzport 8500 --httpaddr $IP --ens-api $IPC
